// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystem.Models;

#nullable disable

namespace ReservationSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514161235_InitialDatabaseSetupWithSeed")]
    partial class InitialDatabaseSetupWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystem.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Intro to Computer Engineering",
                            Name = "CENG101"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Programming Fundamentals",
                            Name = "CENG102"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Data Structures",
                            Name = "CENG201"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Computer Architecture",
                            Name = "CENG202"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Operating Systems",
                            Name = "CENG301"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Database Systems",
                            Name = "CENG302"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Software Engineering",
                            Name = "CENG303"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Computer Networks",
                            Name = "CENG304"
                        },
                        new
                        {
                            Id = 9,
                            Description = "AI and ML",
                            Name = "CENG401"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Capstone Project",
                            Name = "CENG402"
                        });
                });

            modelBuilder.Entity("ReservationSystem.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ReservationSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TermId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TermId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationSystem.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("ReservationSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            FullName = "Admin User",
                            PasswordHash = "AQAAAAIAAYagAAAAEEYZKV51W6JH9ZSoQ98mP5N+8H6Wv+5qqJ8VAk7r8cjDUh4lh63z23LEhkTkiSbh6g==",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 8,
                            Email = "instructor@test.com",
                            FullName = "Instructor User",
                            PasswordHash = "AQAAAAIAAYagAAAAEEYZKV51W6JH9ZSoQ98mP5N+8H6Wv+5qqJ8VAk7r8cjDUh4lh63z23LEhkTkiSbh6g==",
                            Role = "instructor"
                        },
                        new
                        {
                            Id = 16,
                            Email = "cengstmp@gmail.com",
                            FullName = "Test Instructor",
                            PasswordHash = "AQAAAAIAAYagAAAAEEYZKV51W6JH9ZSoQ98mP5N+8H6Wv+5qqJ8VAk7r8cjDUh4lh63z23LEhkTkiSbh6g==",
                            Role = "instructor"
                        });
                });

            modelBuilder.Entity("ReservationSystem.Models.Class", b =>
                {
                    b.HasOne("ReservationSystem.Models.User", "Instructor")
                        .WithMany("PrimaryClassesManaged")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ReservationSystem.Models.Feedback", b =>
                {
                    b.HasOne("ReservationSystem.Models.Class", null)
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClassId");

                    b.HasOne("ReservationSystem.Models.Reservation", "Reservation")
                        .WithMany("FeedbacksReceived")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystem.Models.User", "User")
                        .WithMany("FeedbacksGiven")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReservationSystem.Models.Reservation", b =>
                {
                    b.HasOne("ReservationSystem.Models.Class", "Class")
                        .WithMany("Reservations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystem.Models.User", "Instructor")
                        .WithMany("TaughtReservations")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservationSystem.Models.Term", "Term")
                        .WithMany("Reservations")
                        .HasForeignKey("TermId");

                    b.HasOne("ReservationSystem.Models.User", "User")
                        .WithMany("BookedReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Instructor");

                    b.Navigation("Term");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReservationSystem.Models.Class", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ReservationSystem.Models.Reservation", b =>
                {
                    b.Navigation("FeedbacksReceived");
                });

            modelBuilder.Entity("ReservationSystem.Models.Term", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ReservationSystem.Models.User", b =>
                {
                    b.Navigation("BookedReservations");

                    b.Navigation("FeedbacksGiven");

                    b.Navigation("PrimaryClassesManaged");

                    b.Navigation("TaughtReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
